
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdukmuskbpalfqmjelnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkdWttdXNrYnBhbGZxbWplbG5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4Mzg0ODIsImV4cCI6MjA1OTQxNDQ4Mn0.KEgsCD2VMrEhgrlvY7C7IWbQ0P__8Scyh9sMS2A5vZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});

// Debugging helper function to check for data in tables
export const checkForData = async () => {
  try {
    console.log("Checking for data in ideas table...");
    const { data: ideas, error: ideasError } = await supabase
      .from('ideas')
      .select('*')
      .limit(10);
    
    if (ideasError) {
      console.error("Error fetching ideas:", ideasError);
    } else {
      console.log(`Found ${ideas?.length || 0} ideas:`, ideas);
    }
    
    console.log("Checking for data in hypotheses table...");
    const { data: hypotheses, error: hypothesesError } = await supabase
      .from('hypotheses')
      .select('*')
      .limit(10);
    
    if (hypothesesError) {
      console.error("Error fetching hypotheses:", hypothesesError);
    } else {
      console.log(`Found ${hypotheses?.length || 0} hypotheses:`, hypotheses);
    }
    
    console.log("Checking for data in experiments table...");
    const { data: experiments, error: experimentsError } = await supabase
      .from('experiments')
      .select('*')
      .limit(10);
    
    if (experimentsError) {
      console.error("Error fetching experiments:", experimentsError);
    } else {
      console.log(`Found ${experiments?.length || 0} experiments:`, experiments);
    }
    
    return {
      ideas,
      hypotheses,
      experiments
    };
  } catch (err) {
    console.error("Unexpected error checking for data:", err);
    return null;
  }
};
